server:
  port: 8080
  tomcat:
    threads:
      min-spare: 100
      max: 100
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    web:
      pageable:
        page-parameter: page
        size-parameter: size
        default-page-size: 20
        max-page-size: 2000
        one-indexed-parameters: false
      sort:
        sort-parameter: sortOrder

  ## JPA configuration
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  # dataSource type configuration
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    ## Hikari datasource config
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/tour?serverTimezone = UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234