spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/tour
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/tour
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Cowaine!@#1
      connection-timeout: 5000
      maximum-pool-size: 5
      max-lifetime: 1800000
      idle-timeout: 600000
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  redis:
    url: 127.0.0.1
    port: 19999
    timeout: 1s
    connect-timeout: 3s
    cluster:
      nodes: 127.0.0.1:19999,127.0.0.1:19998,127.0.0.1:19997
      max-redirects: 3
    sentinel:
      master: REDIS_MASTER_NAME
      nodes: 127.0.0.1:19999,127.0.0.1:19998,127.0.0.1:19997
