server:
  port: 8080
  tomcat:
    threads:
      min-spare: 100
      max: 100
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    web:
      pageable:
        page-parameter: page # parameter 이름설정 . 기본 : page
        size-parameter: size
        default-page-size: 20
        max-page-size: 2000
        one-indexed-parameters: false # 1로 시작하고싶으면 true
      sort:
        sort-parameter: sortOrder
  ## JPA configuration
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect #mysql8 버전
    hibernate:
      ddl-auto: none

  # dataSource type configuration
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    ## Hikari datasource config
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/tour?serverTimezone = UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
      connection-timeout: 5000
      maximum-pool-size: 5
      max-lifetime: 1800000
      idle-timeout: 600000
#      connection-test-query: select 1


