server:
  port: 0x628
  tomcat:
    threads:
      min-spare: 100
      max: 100

spring:
  main:
    # 스프링 빈 이름을 중복하여 선언하는 경우 BeanDefinitionOverrideException 예외가 발생하는데,
    # 스프링 프레임워크 5.1.0 버전부터(스프링 부트 2.1.0) 강제로 덮어쓰는 것을 제한한다.
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/tour?serverTimezone = UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 12345
      connection-timeout: 5000
      maximum-pool-size: 5
      max-lifetime: 1800000
      idle-timeout: 600000
      # DataSource 에서 Connection 객체를 받아 올 때는 Connection 객체의 유효 여부를 판단하기 위해 테스트 쿼리를 실행할 수 있다.
      # 성능에 영향을 미치므로 JDBC4를 사용하고 있다면 설정하지 않기를 권고한다.
      connection-test-query: select 1

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    show-sql: false


    # 레디스 한 대
  redis:
    url: 127.0.0.1
    port: 19999
    timeout: 1s           # 레디스 서버에 명령어를 전달하고 결과를 받을 때까지 최대 시간 설정
    connect-timeout: 3s   # 레디스 서버와 클라이언트 사이에 커넥션을 생성할 때 걸리는 최대 시간 설정

    # 레디스 클러스터
    cluster:
      nodes: 127.0.0.1:19999,127.0.0.1:19998,127.0.0.1:19997    # 레디스 클러스터의 노드 주소
      max-redirects: 3    # 잘못된 노드에 데이터를 조회할 때 데이터를 저장한 노드로 리다이렉션하는 횟수

    # 레디스 센티넬
    sentinel:
      master: REDIS_MASTER_NAME                                 # 레디스 센티넬이 모니터링할 레디스 서버 중 마스터 서버 이름
      nodes: 127.0.0.1:19999,127.0.0.1:19998,127.0.0.1:19997    # 레디스 센티넬들의 노드 주소
